package diff

import "testing"

func TestParsePKGINFO(t *testing.T) {
	sample := []byte(`# Generated by melange
pkgname = glibc-locales
pkgver = 2.42-r0
arch = x86_64
size = 16136433
origin = glibc
pkgdesc = GLIBC locale data
url =
commit = eeaa6d73d4eb96d96308dfda6c7a78ce52ee0453
maintainer = wolfi
builddate = 1755630264
license = LGPL-2.1-or-later
depend = merged-lib
`)
	got := parsePKGINFO(sample)
	want := PKGINFOMetadata{
		Description: "GLIBC locale data",
		Arch:        "x86_64",
		License:     "LGPL-2.1-or-later",
		Size:        16136433,
		BuildDate:   1755630264,
	}
	if got != want {
		t.Errorf("parsePKGINFO()\n got: %+v\nwant: %+v", got, want)
	}
}

func TestParsePKGINFO_Empty(t *testing.T) {
	if got := parsePKGINFO(nil); got != (PKGINFOMetadata{}) {
		t.Errorf("empty input: got %+v, want zero", got)
	}
}

func TestParsePKGINFO_Malformed(t *testing.T) {
	// A mix of a valid entry, a comment, a header-less line, and a
	// non-integer where an integer is expected. Only the valid entries
	// should populate; the rest are silently ignored.
	sample := []byte(`# comment
pkgdesc = Only description present
no-equals-sign here
size = not-a-number
builddate = 1234567890
`)
	got := parsePKGINFO(sample)
	want := PKGINFOMetadata{
		Description: "Only description present",
		BuildDate:   1234567890,
	}
	if got != want {
		t.Errorf("malformed: got %+v, want %+v", got, want)
	}
}
